### ISSUE TITLE
Gui intergration

### ISSUE THREAD

**Issue by UkraineBolt** [csc480-19f/LetterLeser#3]
# What do you need done?
Find how to combine reactjs into this project
# Who does it pertain to?
Gui team

**Comment by ghost** [comment]
With Springboot and NPM:
https://dev.to/tzehe/dev-recipes-integrate-react-frontend-in-a-java-corporate-environment-2e43
https://github.com/tzehe/react-spring-example

With Yarn:
https://medium.com/@itzgeoff/including-react-in-your-spring-boot-maven-build-ae3b8f8826e

**Comment by UkraineBolt** [comment]
I found this: 
https://stackoverflow.com/questions/40030580/how-to-run-a-react-app-on-tomcat

**Comment by MikeDoran** [comment]
I looked at that, but the project he's talking about is purely javascript, and doesn't use maven
