### ISSUE TITLE
Database Validation Handler

### ISSUE THREAD

**Issue by UkraineBolt** [csc480-19f/LetterLeser#7]
# What do you need done?
There is a thread that is dedicated to validating the database. This needs to be made and it needs to share a boolean with the main thread so it knows if it needs to wait for the validation thread to finish or not.

**Comment by UkraineBolt** [comment]
@pnguyen3oswego 
Need a method in the db class which I send email in string form and get a list of all emails in return
Don't make it static, otherwise I can't access it

**Comment by Conphucious** [comment]
@UkraineBolt done. Maybe we can use projects to have a dynamic a todo board for the DB/engine/gui. Easier to assign and close out small tasks.
