### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by UkraineBolt** [csc480-19f/LetterLeser#8]
# What do you need done?
We need to look into and document how we are going to run these calculations while also making the class itself

**Comment by UkraineBolt** [comment]
The class has been converted to 6 callables, one for each graph

**Comment by UkraineBolt** [comment]
Sentiment callable is done

**Comment by UkraineBolt** [comment]
heatmap is done but will see if it can be optimized

**Comment by MikeDoran** [comment]
domain callable is done

**Comment by UkraineBolt** [comment]
all methods are done just need testing
