### ISSUE TITLE
Functional Program

### ISSUE THREAD

**Issue by UkraineBolt** [csc480-19f/LetterLeser#9]
# What do you need done?
We need to connect everything into one usable program
This however requires us to finish all other tasks before we tackle this
If you make any progress with interconnecting then please note it here

**Comment by ghost** [comment]
Database & Mailer code migrated. Several functions already written. All we need is an auth key to connect to the mailer and we can use completed db functions. 

Authentication should send over a JSON preferably 
{
    "email": "email_address_value_here",
    "oauth2key": "key_inserted_value_here" 
}

Please put the ReactJS files that authenticate the google login on a dedicated machine that runs 24/7 or toggle-able if possible (for testing). It's a hassle to run extraneous resources on engine side for testing.

**Comment by UkraineBolt** [comment]
Everything works for a single active user except 2 methods that rely on getting emails from db. This is currently untested
